In [10]:
import numpy as np

In [11]:
revenue = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
Ind_rates = 75*revenue

In [12]:
Ind_rates

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [14]:
sales_of_flowers = np.array([[50,60,25] , [10,13,5] , [40,70,52]])
prices_per_units = np.array([20,30,15])

In [15]:
total_sales = sales_of_flowers*prices_per_units
total_sales

array([[1000, 1800,  375],
       [ 200,  390,   75],
       [ 800, 2100,  780]])

In [16]:
total_sale = np.dot(prices_per_units , sales_of_flowers)
total_sales

array([[1000, 1800,  375],
       [ 200,  390,   75],
       [ 800, 2100,  780]])